name: Linux INstall
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
        - name: "Checkout"
          uses: actions/checkout@master
        - name: "Build"
          run: ./scripts/install_ubuntu.sh
          